# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

[tool.poetry]
name = "gitlab-ci-openstack"
version = "0.1.0"
description = "This role provides a setup for GitLab CI in Openstack."
authors = ["Tobias Huste <t.huste@hzdr.de>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
ansible = "^4.2.0"

[tool.poetry.dev-dependencies]
ansible-lint = "^5.0.12"
yamllint = "^1.26.1"
reuse = "^0.13.0"
molecule = {version = "^3.3.4", extras = ["docker"]}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
